
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

